# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

env:
  S3_BUCKET_NAME: be-62-sjuans

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build

    - name: Make zip file #build 후 프로젝트 압축
      run: zip -r ./practice-deploy.zip .
      shell: bash

    - name: Configure AWS credentials # Github Secret에 등록한 (Secret) Access Key 로 권한확인하기(직접 작성 x)
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Upload to S3 # 압축한 프로젝트를 S3로 전송
      run: aws s3 cp --region ap-northeast-2 ./practice-deploy.zip s3://$S3_BUCKET_NAME/practice-deploy.zip

    - name: Code Deploy
      run: > 
        aws deploy create-deployment --application-name be-62-SJUANS
        --deployment-config-name CodeDeployDefault.AllAtOnce
        --deployment-group-name be-62-SJUANS-group
        --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=practice=deploy.zip
